version: '0.1'
services:

  chorizo-with-mustard-db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: chorizo
    container_name: chorizo-with-mustard-db

  chorizo-with-mustard-api:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./api:/chorizo-with-mustard-api
    ports:
      - "8000:8000"
    depends_on:
      - chorizo-with-mustard-db
    container_name: chorizo-with-mustard-api
