import './globals.css'
import 'bootstrap/dist/css/bootstrap.min.css'
import 'bootswatch/dist/flatly/bootstrap.min.css'
import Navbar from './navbar'
import GetUserProfile from './(auth)/profile';
import Script from "next/script";

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
    viewport: 'width=device-width, initial-scale=1'
}

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {

    const user = await GetUserProfile();

    return (
        <html lang="en">
            <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" defer />
            <body>
                <Navbar {...user} />
                {children}
            </body>
        </html>
    )
}
